name: Test .md files on PRs
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - "docs/**.md"

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: node script/pr-test.js